proxy_cache_valid 1m;
proxy_cache_key $scheme$host$request_uri;
proxy_cache_path /var/angie_cache levels=1:2 keys_zone=one:10m:file=/etc/angie/cache.state inactive=48h
max_size=800m;

ssl_session_cache shared:SSL:1m;
ssl_session_timeout 24h;

ssl_session_tickets on; # включено по умолчанию, но пропишем явно

limit_req_zone $binary_remote_addr zone=lone:10m rate=1r/s;

error_log /var/log/angie/error.log warn;
access_log /var/log/angie/access.log;

server {
    listen 80;
    listen [::]:80;

    server_name otus-angie-14.s7h.ru;

    return 301 https://otus-angie-14.s7h.ru$request_uri;

}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic reuseport;

    http2 on;
    http2_max_concurrent_streams 128;
    http2_chunk_size 8k;

    http3 on;
    add_header Alt-Svc 'h3=":443"; ma=86400';

    server_name otus-angie-14.s7h.ru;

    ssl_certificate /etc/letsencrypt/live/otus-angie-14.s7h.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/otus-angie-14.s7h.ru/privkey.pem;

    add_header Strict-Transport-Security max-age=3600; # HSTS на час

    index index.php index.html index.htm;

    root /var/www/html;

    location /wp-admin/ {
        allow 76.78.152.0/21;
        deny all;

        try_files $uri $uri/ /wp-admin/index.php$is_args$args;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        limit_req zone=lone burst=5;
        limit_req_log_level error;
        limit_req_status 503;

        gzip on;
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location =/favicon.ico
 	         =/robots.txt {
        proxy_cache one;
        proxy_cache_valid 200 1h;
        proxy_cache_lock on;
        proxy_cache_min_uses 2;
        proxy_ignore_headers "Cache-Control" "Expires";
        proxy_cache_use_stale updating error timeout invalid_header http_500 http_502 http_504;
        proxy_cache_background_update on;
        log_not_found off;
    }

    location /wp-includes/
             /wp-content/uploads/ {
        expires max;
    }

    location ~* \.(gif|ico|jpeg|jpg|png|pdf)$ {
        expires max;
        log_not_found off;
    }

    location ~* \.(css|js|svg)$ {
        gzip on;
        gzip_static on;
        gzip_types text/plain text/css text/xml application/javascript application/json image/svg+xml
        expires max;
        log_not_found off;
    }

    location .well-known/acme-challenge/ {
        alias /var/acme-challenge/;
    }
}
